trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: SSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    runOptions: 'commands'
    commands: |
      echo "🚀 Deploy started"

      cd ~

      # remove old project
      rm -rf app

      # clone fresh repo
      git clone https://github.com/tanishka-tanu/Automated-Node-Application.git app

      cd app

      # build docker image
      sudo docker build -t node-devops-app .

      # stop old container
      sudo docker rm -f $(sudo docker ps -aq) || true

      # run new container
      sudo docker run -d -p 3000:3000 node-devops-app
  displayName: "Deploy to VM"