trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# 1️⃣ COPY CODE FROM AZURE PIPELINE TO VM
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/tanu/app'
  displayName: "Copy code to VM"

# 2️⃣ BUILD + RUN ON VM
- task: SSH@0
  inputs:
    sshEndpoint: 'azure-vm-ssh'
    runOptions: 'commands'
    commands: |
      echo "🚀 Deploying App"

      cd /home/tanu/app

      sudo docker build -t node-devops-app .

      sudo docker rm -f $(sudo docker ps -aq) || true

      sudo docker run -d -p 3000:3000 node-devops-app
  displayName: "Run Docker on VM"